accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finlife/', include('finlife.urls')),
]

boards/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Board(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ('title', 'content', )

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', )

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.views.decorators.http import require_http_methods

# Create your views here.
@require_http_methods(["GET"])
def index(request):
    boards = Board.objects.all().order_by('-created_at')
    context = {
        'boards': boards
    }
    return render(request, 'boards/index.html', context)

@require_http_methods(["GET", "POST"])
def detail(request, pk):
    board = get_object_or_404(Board, pk=pk)
    if request.method == 'POST':
        board.delete()
        return redirect('boards:index')

    comments = board.comments.all()
    comment_form = CommentForm()
    
    context = {
        'board': board,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, 'boards/detail.html', context)

@require_http_methods(["GET", "POST"])
def update(request, pk):
    board = get_object_or_404(Board, pk=pk)

    if request.method == 'POST':
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            form.save()
            return redirect('boards:detail', board.pk)
    else:
        form = BoardForm(instance=board)
    context = {
        'board': board,
        'form': form,
    }        
    return render(request, 'boards/update.html', context)

@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST, request.FILES)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user
            board.save()
            return redirect('boards:index')
    else:
        form = BoardForm()
    context = {
        'form': form,
    }
    return render(request, 'boards/create.html', context)

@require_http_methods(["POST"])
def comment(request, board_pk):
    if not request.user.is_authenticated:
        return redirect('accounts:login')
    
    board = Board.objects.get(pk=board_pk)
    comment_form = CommentForm(request.POST)

    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.board = board
        comment.author = request.user
        comment.save()
        return redirect('boards:detail', board.pk)


@require_http_methods(["POST"])
def comment_detail(request, board_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.author:
            comment.delete()
        return redirect('boards:detail', board_pk)

boards/templates/boards/create.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">생성 페이지</h1>
  <form action="{% url 'boards:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-light">생성하기</button>
  </form>
</div>
{% endblock content %}

boards/templates/boards/detail.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">상세 페이지</h1>
  </div>
  <p>글번호 : {{ board.id }}</p>  
  <p>글제목 : {{ board.title }}</p>
  <p>글내용 : {{ board.content }}</p>
  <p>작성날짜 : {{ board.created_at }}</p>
  <p>수정날짜 : {{ board.updated_at }}</p>
  <hr>
  <div class="mb-5 d-flex justify-content-between">
    <a href="{% url 'boards:index' %}"><button class="btn btn-light">메인 페이지로</button></a>
    {% if request.user.is_authenticated %}
    <div class="d-flex">
      <a href="{% url 'boards:update' board.id %}"><button class="me-3 btn btn-success">수정하기</button></a>
      <form action="{% url 'boards:detail' board.id%}" method='POST'>
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">삭제하기</button>
      </form>
    </div>
    {% endif %}
  </div>

  {% if request.user.is_authenticated %}
  <form action="{% url 'boards:comment' board.id %}" method='POST'>
    {% csrf_token %}
    <button class="btn btn-secondary" style="float: right;" type="submit">작성하기</button>
    {{ comment_form.as_p }}
  </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">댓글을 작성하시려면 로그인을 해주세요.</a>
  {% endif %}

  <div class="mt-5">
    {% if comments|length == 0 %} 댓글이 없습니다.
    {% else %}
      {% for comment in comments %}
      <div class="my-3 d-flex justify-content-between">
        <div>
          <span>{{ comment.author }} - {{ comment.content }}</span>
          <span class="mx-5">({{ comment.created_at }})</span>
        </div>
          <div>
            {% if request.user == comment.author %}
            <form action="{% url 'boards:comment_detail' board.id comment.id %}" method='POST'>
              {% csrf_token %}
              <button class="btn btn-light">삭제하기</button>
            </form>
            {% endif %}
          </div>
        </div>
        <hr/>
      {% endfor %}
    {% endif %}
  </div>
</div>
{% endblock content %}

boards/templates/boards/index.html
{% extends 'base.html' %}

{% block content %}
<div>
  <div class="d-flex justify-content-between">
    <h1 class="mb-4">메인 페이지</h1>
    {% if request.user.is_authenticated %}
    <a style="height: 70%;" href="{% url 'boards:create' %}"><button class="btn btn-info">생성하기</button></a>
    {% endif %}
  </div>
  {% if boards|length == 0 %}아직 게시글이 없습니다
  {% else %}
  {% for board in boards %}
    <p>글번호 : {{ board.id }}</p>  
    <p>작성자 : <a href="{% url 'accounts:profile' board.author %}">{{ board.author }}</a></p>
    <p>글제목 : <a href="{% url 'boards:detail' board.id %}">{{ board.title }}</a></p>
    <hr>
  {% endfor %}
  {% endif %}
</div>
{% endblock content %}

boards/templates/boards/update.html
{% extends 'base.html' %}

{% block content %}
<div>
  <h1 class="mb-4">수정 페이지</h1>
  <form action="{% url 'boards:update' board.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
</div>
{% endblock content %}