accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finlife/', include('finlife.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    

boards/models.py
from django.db import models
from django.conf import settings


# Create your models here.
class Board(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()


class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from django.contrib.auth import get_user_model
from django.views.decorators.http import require_POST


# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('boards:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


def logout(request):
    auth_logout(request)
    return redirect('boards:index')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('boards:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person': person,
        }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_user_model().objects.get(pk=user_pk)
        if request.user in person.followers.all():
            person.followers.remove(request.user)
        else:
            person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    else:
        return redirect('accounts:login')

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}

    <div class="d-flex mb-3">
        <div class="me-auto p-2"><h1>{{ person.username }}님의 프로필 페이지</h1></div>
    
        <div class="p-2">
        팔로잉 : {{ person.followings.all | length }} / 팔로워 : {{ person.followers.all | length }}
        </div>
        <div class="p-2">
        {% if request.user != person %}
            <form action="{% url 'accounts:follow' person.pk %}" method="POST">
                {% csrf_token %}
                {% if request.user in person.followers.all %}
                    <button class="btn btn-light">Unfollow</button>
                {% else %}
                    <button class="btn btn-light">Follow</button>
                {% endif %}
            </form>
        {% endif %}
        </div>

    </div>


    <div>
        <p>회원번호 {{ person.pk }}</p>
        <p>유저이름 {{ person.username }}</p>
        <p>가입날짜 {{ person.date_joined }}</p>
    </div>
    
    <hr>

    <h3>{{ person.username }}가 쓴 글</h3>
    {% for board in person.board_set.all %}
        <div class="card bg-light m-2 border-0 h-auto">
            <div class="card-body">
                <p>글 번호: {{ board.pk }}</p>
                <div>글 제목 : <a href="{% url 'boards:detail' board.id %}">{{ board.title }}</a></div>
            </div>
        </div>
    {% endfor %}

    <hr>

    <h3>{{ person.username }}가 쓴 댓글</h3>
    {% for comment in person.comment_set.all %}
        <div class="card bg-light m-2 border-0 h-auto">
            <div class="card-body">
                <div>{{ comment.content }}</div>
            </div>
        </div>
    {% empty %}
        <div>아직 작성한 댓글 없습니다.</div>
    {% endfor %}

    <hr>

    <h3>팔로워</h3>
    {% for follower in person.followers.all %}
        <a href="{% url 'accounts:profile' follower.username%}">{{ follower.username }}</a>
    {% empty %}
        <div>팔로워 한 사람이 없습니다.</div>
    {% endfor %}    

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>SignUp</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>

{% endblock content %}