accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finlife/', include('finlife.urls')),
]

templates/_navbar.html
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'boards:index' %}">메인 페이지</a>
        </li>
        <li class="nav-item">
        {% if user.is_authenticated %}
          <a class="nav-link" aria-current="page" href="{% url 'accounts:profile' user.username %}">프로필 페이지</a>
        {% else %}
          <a class="nav-link" aria-current="page" href="{% url 'accounts:login' %}">프로필 페이지</a>
        {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
</head>
<body>
  <div class="mt-3 container">
    <div class="mb-5">
      {% if request.user.is_authenticated %}
      <div class="d-flex justify-content-between">
        <h3>Hello, {{ user }} </h3>
        <div>
          <form action="{% url 'accounts:logout' %}"method="POST">
            {% csrf_token %}
            <button class="btn btn-light">Logout</button>
          </form>
        </div>
      </div>
      <hr>
      <div class="mt-3 mb-4">
        {% include '_navbar.html' %}
      </div>
      {% else %}
      <div class="d-flex justify-content-between">
          <h3>로그인을 해주세요</h3>
          <div>
          <a href="{% url 'accounts:login' %}" class="btn btn-light">Login</a>
          <a href="{% url 'accounts:signup' %}" class="btn btn-light">Signup</a>
          </div>
      </div>
      <hr>
      <div class="mt-3 mb-4">
        {% include '_navbar.html' %}
      </div>
      {% endif %}

      {% block content %}
      {% endblock content %}
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>